Added Christmas themed Hubber
EddieHubCommunity/Branding pull request #40
Opened 2021-12-02 12:29 UTC by avneesh0612

I have added a new Hubber, which is Christmas-themed!

2021-12-02 12:32 UTC, krishguptadev requested changes
A file should be added, rather than a link, add in `community/`

2021-12-02 12:33 UTC, avneesh0612 commented
oh okay

2021-12-02 12:40 UTC, avneesh0612 commented
Good now? @krishguptadev

2021-12-02 13:11 UTC, krishguptadev commented on README.md
> +![23](https://user-images.githubusercontent.com/76690419/144421989-00568b89-37c8-4310-9ed9-a2dc89e6ed9e.png)
This shouldn't be here afaik

2021-12-02 13:50 UTC, avneesh0612 commented on README.md
> +![23](https://user-images.githubusercontent.com/76690419/144421989-00568b89-37c8-4310-9ed9-a2dc89e6ed9e.png)
hmm, but all images should be in readme, right?

2021-12-03 03:00 UTC, krishguptadev commented on README.md
> +![23](https://user-images.githubusercontent.com/76690419/144421989-00568b89-37c8-4310-9ed9-a2dc89e6ed9e.png)
the community-made ones are not there tho

2021-12-03 03:02 UTC, eddiejaoude commented on README.md
> +![23](https://user-images.githubusercontent.com/76690419/144421989-00568b89-37c8-4310-9ed9-a2dc89e6ed9e.png)
Good spot Krish 👍 the `README.md` is only for the official images

A `community.md` could be added though 👍

2021-12-03 05:48 UTC, avneesh0612 commented on README.md
> +![23](https://user-images.githubusercontent.com/76690419/144421989-00568b89-37c8-4310-9ed9-a2dc89e6ed9e.png)
Oh okay cool

2021-12-03 06:33 UTC, avneesh0612 commented
Removed them 👍

2021-12-03 06:44 UTC, krishguptadev approved these changes
Awesome!

2021-12-11 05:06 UTC, eddiejaoude approved these changes
Thank you 👍

2021-12-11 05:06 UTC, merged